### ISSUE TITLE
特殊样本（得到的json有乱码无法正常解析）

### ISSUE THREAD

**Issue by caoyang131** [number201724/psbfile#1]
这个样本转化后的json带有乱码无法正常解析，求分析
[filelist.zip](https://github.com/number201724/psbfile/files/1834125/filelist.zip)

**Comment by number201724** [comment]
您好解密出来的JSON文件请使用UTF8编码打开。

**Comment by caoyang131** [comment]
我试过用UTF8编码打开过，大部分字符都是正确的，尾部出现了：
{
     ....
    "ev101a2" : 586,
     "ev101a3" : 587,
     "�" : 708
}
这样的字符导致无法用pcc转换回psb，麻烦再看一下

**Comment by number201724** [comment]
最后一个文字是SHIFT-JIS的字符串全角空格，请自己编写工具转换.

**Comment by caoyang131** [comment]
好的，多谢指点
